// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Angy.BackEnd.Kharonte.Data.Migrations
{
    [DbContext(typeof(KharonteContext))]
    class KharonteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("Relational:MaxIdentifierLength", value: 63)
                .HasAnnotation("ProductVersion", "5.0.0-preview.7.20365.15");

            modelBuilder.Entity("Angy.BackEnd.Kharonte.Data.Model.Photo", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Extension")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Filename")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Instant>("Inserted")
                    .HasColumnType("timestamp");

                b.Property<string>("Path")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("PendingPhotos");
            });
#pragma warning restore 612, 618
        }
    }
}